add dockerfile and components
Gamify-IT/sharry-fileserver pull request #2
Opened 2023-04-10 19:49 UTC by madebyTimo

This PR adds the components for our sharry fileserver image.

Please merge after https://github.com/Gamify-IT/sharry-fileserver/pull/1 

To test run `docker compose up --build` and test if the fileserver is accessible via http://localhost/fileserver/ and the login via keycloak works.

Please use the corresponding keycloak test-data for testing.

2023-04-10 20:52 UTC, madebyTimo commented
Please also review the corresponding test-data https://github.com/Gamify-IT/test-data/pull/22

2023-04-11 10:43 UTC, programminghoch10 requested changes

2023-04-11 10:43 UTC, programminghoch10 commented on sharry.conf
> +          id = "gameify-it"
```suggestion
          id = "gamify-it"
```

2023-04-11 10:43 UTC, programminghoch10 commented on .github/workflows/deploy-docker-image-on-release.yml
> +        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
```suggestion
        uses: docker/login-action@v2
```

2023-04-11 10:43 UTC, programminghoch10 commented on .github/workflows/deploy-docker-image-on-release.yml
> +        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
```suggestion
        uses: docker/metadata-action@v4
```

2023-04-11 10:43 UTC, programminghoch10 commented on .github/workflows/deploy-docker-image-on-release.yml
> +        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
```suggestion
        uses: docker/build-push-action@v3
```

2023-04-11 14:08 UTC, Aaron2000119 commented
While running it on windows, i get this error `': No such file or directory't execute 'bash` in the fileserver container.

2023-04-11 15:47 UTC, madebyTimo commented
@Aaron2000119 on Linux there is no such problem, can you provide the full logs?

2023-04-11 16:30 UTC, Aaron2000119 commented
': No such file or directoryn't execute 'bash
': No such file or directoryn't execute 'bash
': No such file or directoryn't execute 'bash
': No such file or directoryn't execute 'bash
': No such file or directoryn't execute 'bash
': No such file or directoryn't execute 'bash
': No such file or directoryn't execute 'bash
': No such file or directoryn't execute 'bash
': No such file or directoryn't execute 'bash
fileserver exited with code 127

2023-04-11 20:37 UTC, madebyTimo commented
We solved the problem. It was caused by wrong line-endings

2023-04-11 21:55 UTC, programminghoch10 requested changes

2023-04-11 21:55 UTC, programminghoch10 commented on docker-compose.yaml
> +      - "80:80"
Newline at the end makes the file look cleaner.
```suggestion
      - "80:80"

```

2023-04-11 21:55 UTC, programminghoch10 commented on entrypoint.sh
> +exec "$@"
```suggestion
exec "$@"

```

2023-04-12 20:33 UTC, programminghoch10 approved these changes

2023-04-12 20:43 UTC, Aaron2000119 approved these changes

2023-04-12 20:44 UTC, merged